using System;
using System.Collections.Generic;
using System.Linq;

namespace XM.ConfigNew.Metadata
{
    /// <summary>
    /// 配置索引元数据 - 描述配置类的索引定义
    /// 支持单字段索引和复合索引(多字段)
    /// </summary>
    public class ConfigIndexMetadata
    {
        #region 基础信息
        
        /// <summary>
        /// 索引名称(来自[XmlIndex]特性)
        /// </summary>
        public string IndexName;
        
        /// <summary>
        /// 参与此索引的字段列表(按Position排序)
        /// </summary>
        public List<ConfigFieldMetadata> IndexFields;
        
        #endregion
        
        #region 索引类型
        
        /// <summary>
        /// 是否为唯一索引(一对一映射)
        /// true: 每个索引值对应唯一的配置
        /// false: 每个索引值可能对应多个配置
        /// </summary>
        public bool IsUnique;
        
        /// <summary>
        /// 是否为多值索引(来自[XmlIndex(isMultiValue=true)])
        /// 用于一对多的关系
        /// </summary>
        public bool IsMultiValue;
        
        #endregion
        
        #region 代码生成信息
        
        /// <summary>
        /// 生成的索引结构体名称
        /// 例如: "NameIndex" 对应 struct NameIndex : IConfigIndexGroup&lt;T&gt;
        /// </summary>
        public string GeneratedStructName;
        
        /// <summary>
        /// 生成的查询方法名称
        /// 例如: "GetByName" 或 "GetByNameAndLevel"
        /// </summary>
        public string GeneratedQueryMethodName;
        
        /// <summary>
        /// 是否为 XMLLink 自动生成的索引
        /// 用于区分用户手动定义的索引和系统为 XMLLink 自动生成的索引
        /// </summary>
        public bool IsAutoGeneratedForLink;
        
        #endregion
        
        #region 属性
        
        /// <summary>
        /// 是否为复合索引(多字段)
        /// </summary>
        public bool IsCompositeIndex => IndexFields != null && IndexFields.Count > 1;
        
        /// <summary>
        /// 是否为单字段索引
        /// </summary>
        public bool IsSingleFieldIndex => IndexFields != null && IndexFields.Count == 1;
        
        #endregion
        
    }
}
